# g-xTB parameter schema mapping
# Indices are 0-based [line, column] within each element block (lines) or the
# two global lines at the top of parameters/gxtb (global_lines).

[repulsion]
# Element-wise indices into each Z block
z_eff0 = [7, 0]    # example: line8 col0
alpha0 = [7, 2]
kq     = [7, 3]
kq2    = [7, 4]
kcn    = [7, 6]
r0     = [8, 0]

# Global indices into the two global lines at top
kpen1_hhe  = [0, 0]
kpen1_rest = [0, 1]
kpen2      = [0, 2]
kpen3      = [0, 3]
kpen4      = [0, 4]
kexp       = [0, 5]

[cn]
r_cov = [1, 0]   # element covalent radius per Z block
k_cn  = [1, 6]   # global CN steepness from global line

[increment]
delta_e_incr = [8, 7]

# NOTE: The above indices are only illustrative. Please update them to the
# correct positions per your g-xTB parameter specification, then copy this file
# to `parameters/gxtb.schema.toml`.

[diatomic]
# Channel scaling factors k_sigma(Z), k_pi(Z), k_delta(Z)
sigma = [0, 0]  # placeholder indices inside each element block
pi    = [0, 1]
delta = [0, 2]

[eht]
# Onsite base energies ε^0_l (or h_l) per shell; one value per element
eps_s = [0, 0]
eps_p = [0, 1]
eps_d = [0, 2]
eps_f = [0, 3]

# Linear CN fallback coefficients (if no polynomial) k_ho_l
k_ho_s = [1, 0]
k_ho_p = [1, 1]
k_ho_d = [1, 2]
k_ho_f = [1, 3]

# Wolfsberg per shell k_w_l
k_w_s = [2, 0]
k_w_p = [2, 1]
k_w_d = [2, 2]
k_w_f = [2, 3]

# Electronegativity per element and global scaling (global lines)
en    = [3, 0]
k_en  = [0, 6]   # example: from a global line

# CN polynomial coefficients (degree 4 ⇒ 5 coeffs) per shell: provide a list of indices
pi_cn_s = [[4,0],[4,1],[4,2],[4,3],[4,4]]
pi_cn_p = [[4,5],[4,6],[4,7],[4,8],[4,9]]
pi_cn_d = [[5,0],[5,1],[5,2],[5,3],[5,4]]
pi_cn_f = [[5,5],[5,6],[5,7],[5,8],[5,9]]

# Distance polynomial Π_{ll'}(R) degree 3 ⇒ 4 coeffs per shell pair class
pi_r_ss = [[6,0],[6,1],[6,2],[6,3]]
pi_r_sp = [[6,4],[6,5],[6,6],[6,7]]
pi_r_pp = [[6,8],[6,9],[6,10],[6,11]]
pi_r_sd = [[7,0],[7,1],[7,2],[7,3]]
pi_r_pd = [[7,4],[7,5],[7,6],[7,7]]
pi_r_dd = [[7,8],[7,9],[7,10],[7,11]]
pi_r_sf = [[8,0],[8,1],[8,2],[8,3]]
pi_r_pf = [[8,4],[8,5],[8,6],[8,7]]
pi_r_df = [[8,8],[8,9],[8,10],[8,11]]
pi_r_ff = [[8,12],[8,13],[8,14],[8,15]]

