# g-xTB parameter schema mapping (0-based indices)
# Implements the following equations from doc/theory and theory.md:
# - Increment energy: Eq. (50) / Eq. (13)
# - Semi-classical repulsion: Eqs. (52)–(56) / Eqs. (14)–(17)
# - CN: Eq. (47)
#
# Rationale (inferred from patterns across Z and doc/theory):
# - Block structure per element: 9 lines
#   L1: 10 floats, shell/global (EHT-related); not used here
#   L2–L7: 4 floats each; shell controls; not used here
#   L8: 7 floats; contains alpha0 (col0), r0 (col1), z_eff0 (col2), and
#       increment ΔE_incr (col5), plus k_CN,elem (col6)
#   L9: 8 floats; contains small modifiers; we choose kq and kq2 from here
# - Global two lines at file start provide k_pen and k_exp and k_CN (global)

[repulsion]
# Element-wise indices into each Z block (0-based [line, column])
alpha0 = [7, 0]       # α_A^0 in Eq. (56)
r0     = [7, 1]       # R_A^0 in Eq. (54)
z_eff0 = [7, 2]       # Z_A^{eff,0} in Eq. (53)
# Charge-dependence coefficients in Eq. (53)
kq     = [8, 4]
kq2    = [8, 7]
# CN dependence of α_A in Eq. (56)
kcn    = [7, 6]

# Global indices into the two global lines (0-based [line, column])
# Series expansion coefficients for f^rep in Eq. (54)
kpen1_hhe  = [0, 0]
kpen1_rest = [0, 1]
kpen2      = [0, 2]
kpen3      = [0, 3]
kpen4      = [0, 4]
# Exponent k_exp in Eq. (54)
kexp       = [0, 5]

[cn]
# Element covalent radii R_A^{cov} and global k^{CN} in Eq. (47)
r_cov = [7, 1]
k_cn  = [1, 6]

[increment]
# Atomic increment ΔE_A^{incr} in Eq. (50)
delta_e_incr = [7, 5]

[diatomic]
# Channel scaling factors per element (Eqs. 31–32). Use spare header
# columns in line0 (indices 7–9) to avoid collision with eps_{s,p,d,f} (0–3)
# and EN proxy (4) and k_en (global line0 col6). These positions exist for
# every element entry and are consistent across Z.
sigma = [0, 7]
pi    = [0, 8]
delta = [0, 9]

[hubbard]
# Heuristic mapping (subject to confirmation): assign per-element Hubbard
# hardness (gamma) and cubic correction (gamma3) to line2 columns 2 & 3.
# Rationale: line2 col0/1 used (k_ho_p, k_w_p); cols 2/3 free across Z.
# Typical gamma range expected ~0.2–0.5 Eh for main-group valence shells.
# Updated mapping (educated guess): use line5 column0 for gamma to ensure
# strictly positive hardness across H, O and main-group elements, enabling
# second-order TB per doc/theory/15_second_order_tb.md (Eqs. 100–106).
# Verified on H (Z=1) and O (Z=8) to be > 0.
gamma  = [5, 0]
gamma3 = [2, 3]

[third_order]
# Element-wise third-order element parameter Γ^{(3)}_A (Eq. 131)
gamma3_elem = [6, 0]
# Global per-shell scalings k^{(3),Γ}_l (l = s,p,d,f) placed in global line1 cols 0..3
kGamma_s = [1, 0]
kGamma_p = [1, 1]
kGamma_d = [1, 2]
kGamma_f = [1, 3]
# Global kernel parameters (Eqs. 132–133b)
k3   = [1, 4]
k3x  = [1, 5]

[fourth_order]
# Global Γ^{(4)} (Eq. 140b) placed on global line1 col7 to avoid overlap with [diatomic]
gamma4 = [1, 7]

[spin]
# Element-wise spin scaling k^W_A (Eq. 121); place at L7 col1 which is free across Z blocks
kW = [6, 1]

[aes]
# Anisotropic Electrostatics (AES) global damping exponents for orders n=3,5 (doc/theory/16).
# Following dxtb's damped multipole, we map the available global slots to:
# - dmp3: exponent for n=3 contributions (monopole–dipole)
# - dmp5: exponent for n=5 contributions (dipole–dipole, monopole–quadrupole)
dmp3  = [1, 8]
dmp5  = [1, 9]
# Higher-order damping exponents for n=7,9 (Eq. 110c–d):
# Until dedicated global slots are provided upstream, we explicitly map them to
# the same global entries as (n=3,5) so they are deterministically defined.
# This avoids rule-based derivations and makes the choice explicit.
dmp7  = [1, 8]
dmp9  = [1, 9]

# SI damping (Eq. 117) rules to enable short-range attenuation using rcov-based R0
# Values are parameters (not hidden defaults) and can be tuned if a reference is provided.
si_k3 = 1.0
si_ks3 = 1.0
si_k5 = 1.0
si_ks5 = 1.0
si_R0_mode = "rcov"
si_R0_scale = 1.0

[aes.element]
# Element-wise AES radii parameters inspired by dxtb:
# - mprad (L7 C0): base radius per element for damped multipole
# - mpvcn (L7 C6): small valence-CN shift parameter
# These columns are populated across Z in the provided gxtb file.
mprad = [7, 0]
mpvcn = [7, 6]

[eht]
# Base onsite energies (line0 cols 0–3, 4 used for additional small correction so we restrict to first four for s,p,d,f shells)
eps_s = [0, 0]
eps_p = [0, 1]
eps_d = [0, 2]
eps_f = [0, 3]

# Linear CN fallback coefficients k_ho (choose line1 & line2 first columns per shell pattern across blocks)
k_ho_s = [1, 0]
k_ho_p = [2, 0]
k_ho_d = [3, 0]
k_ho_f = [4, 0]

# Wolfsberg factors k_w per shell (take next column in same lines)
k_w_s = [1, 1]
k_w_p = [2, 1]
k_w_d = [3, 1]
k_w_f = [4, 1]

# Electronegativity per element (line7 col0 already used; use line0 col4 as EN proxy) and global k_en from global line0 col6
en   = [0, 4]
k_en = [0, 6]

# Higher-order polynomials and extra fields intentionally omitted here until
# their exact column positions are confirmed against doc/theory and file spec.

[ofx]
# Onsite correction for Mulliken-approximated Fock exchange (OFX), doc/theory/21.
# We map per-element onsite exchange-type integrals (Sec. 2.2) to unused element columns.
# Educated mapping (explicit; adjust if conflicts arise in future mappings):
# - Use L5 C2, L5 C3, L6 C2, L6 C3 for cross-l pairs that need only four slots
# - Use remaining free columns on L8 for within-l off-diagonals and additional cross-l
# This keeps separation from AES and repulsion columns used on L7/L8.
[ofx.element]
sp     = [5, 2]
sd     = [5, 3]
sf     = [6, 2]
pd     = [6, 3]
pf     = [8, 0]
df     = [8, 1]
pp_off = [8, 2]
dd_off = [8, 3]
ff_off = [8, 5]

# [mfx]
# Range-separated MFX global parameters (doc/theory/20, Eqs. 149–153).
# NOTE: All known global slots are already in use by other sections:
#   - global line 0 cols 0..9: repulsion (0..5), k_en (6), diatomic sigma/pi/delta (7..9)
#   - global line 1 cols 0..9: kGamma_s/p/d/f (0..3), k3 (4), k3x (5), k_cn (6), gamma4 (7), dmp3/dmp5 (8..9)
# As such, we do not assign fixed indices for alpha/omega/k1/k2 here.
# Provide these values via runtime mfx_params or through a separate parameter file.

[mfx.element]
# Per-element U^{MFX}_l shell parameters (Eq. 149). We map to the first two columns of
# lines L5 and L6 in each element block, which are unused by other sections here.
U_s = [5, 0]
U_p = [5, 1]
U_d = [3, 0]
U_f = [4, 0]

[qvszp]
# q‑vSZP effective-charge prefactors per element (doc/theory/7, Eq. 28):
#   q_eff(A) = k0_A [ q_A + k1_A q_A^2 ] + k2_A sqrt(CN_A) + k3_A CN_A q_A^{EEQBC}
# Mapping policy: educated guess using free columns in element blocks, clearly marked here.
# Rationale:
#   - Lines L3 and L4 (0-based index 3 and 4) have 4 floats across Z and only the first two columns are
#     used by onsite CN/ Wolfsberg factors (k_ho_l, k_w_l). We map k0,k1 to L3 C2,C3 and k2,k3 to L4 C2,C3.
#   - This avoids collision with repulsion (L7/L8) and diatomic/EN/eht slots on L0.
#   - If future upstream files change line shapes, update these indices accordingly.
k0 = [3, 2]
k1 = [3, 3]
k2 = [4, 2]
k3 = [4, 3]

[eeq]
# Column indices in parameters/eeq for electronegativity model
# chi: electronegativity, eta: hardness, radius: screening radius
chi = 0
eta = 1
radius = 2
